{{- if not .Values.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubevirt-management.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevirt-management.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientSecret: {{ required ".Values.auth.clientSecret is required when no existingSecret is set" .Values.auth.clientSecret | quote }}
  sessionHashKey: {{ required ".Values.auth.sessionHashKey is required when no existingSecret is set (generate with `openssl rand -hex 64`)" .Values.auth.sessionHashKey | quote }}
  sessionBlockKey: {{ required ".Values.auth.sessionBlockKey is required when no existingSecret is set (generate with `openssl rand -hex 32`)" .Values.auth.sessionBlockKey | quote }}
{{- end }}
